### ISSUE TITLE
Oppgave I

### ISSUE THREAD

**Issue by CKolle** [CKolle/Prosjekt-del-2#28]
Enten lag funksjoner som lagrer og leser inn steder fra en egen sted-fil, eller utvid funksjonene fra øving 9 slik at de også lagrer og leser inn stedlista. Avgjør om stedene skal lagres i samme fil som avtalene eller i sin egen fil.

**Comment by Tinnitussen** [comment]
@hakonjm Greit hvis du kan fullføre oppgavene du har satt deg selv opp på, siden det er vanskelig å fortsette med resten av oppgavene uten at dette er fullført.
