### ISSUE TITLE
Oppgave L

### ISSUE THREAD

**Issue by CKolle** [CKolle/Prosjekt-del-2#31]
Endre funksjonen som lagrer avtaler til fil slik at den også lagrer kategori-lista samt lagrer sted korrekt som et objekt heller som en streng. Endre funksjonen som leser inn avtaler fra fil slik at den først leser inn kategoriene og stedene og deretter leser inn avtalene.

- a. Hint: Når dere lagrer kategori-lista til en avtale til fil, kan dere lagre kategori-lista som ei komma-separert liste med id-ene til kategoriene. Når dere laster inn dataene, last inn kategoriene før avtalene. Når dere deretter leser inn kategori-lista til avtalene, ta hver ID i lista over kategorier og finn kategori-objektet med den ID-en i hele lista over kategorier. Slik kan dere rekonstruere kategori-lista fra ei tekstfil. Gjør tilsvarende for stedobjektene.

**Comment by Tinnitussen** [comment]
Hvordan lag_avtale() funksjonen henter sted må endres til å velge objekt fra en liste når menyvalg for å legge til steder lages.
Prøvde å gjøre oppgaven på en måte uten å ødelegge programmet. Legg merke til at les_avtaler() nå returnerer en dictionary med 3 lister i stedet for en liste. Endret også menyvalget for å lese avtale slik at denne endringen ikke ødelegga programmet.
